### ISSUE TITLE
HTML panels misses files

### ISSUE THREAD

**Issue by schroef** [reimund/Save-Panel#5]
I wanted to try installing the HTML panel, seems files are missing. Its linking to files which are not in this repo.

```
styles/app.css
js/all.js
js/CSInterface.js
```

**Comment by schroef** [comment]
Not sure why, but you've added app.css to your gitnore file???

html-panel/src/styles/app.css

**Comment by reimund** [comment]
This issue seems to belong to the Tych Panel repo.

Those files are being built by gulp or added by the packaging script, that's why they are ignored.
